var currentView='dashboard';
var currentRole='Admin';
var metrics=[['128','Total Students','+6 this month','icon-students'],['87%','Attendance Today','111 / 128 present','icon-check'],['14','Ready for Promotion','View list','icon-belt'],['RWF 245k','Pending Payments','23 invoices','icon-payments'],['RWF 1.245M','Monthly Revenue','May 2025','icon-report']];
var schedule={Monday:[['13:00-14:00','Women’s Lesson','women','Focused training'],['17:00-17:55','Kid Lesson','kid','Ages 6-10'],['18:00-18:55','Teen & Adults','teen','Above 11'],['19:00-19:55','Teen & Adults','teen','Above 11']],Tuesday:[['16:00-16:55','Kid Lesson','kid','Ages 6-10'],['17:00-17:40','Little Dragon','dragon','Ages 3-5'],['18:00-18:55','Kid Lesson','kid','Ages 6-10'],['19:00-19:55','Sparring Lesson','sparring','Blue belt+']],Thursday:[['17:00-17:55','Kid Lesson','kid','Ages 6-10'],['18:00-18:55','Teen & Adults','teen','Above 11']],Friday:[['14:00-14:55','Sparring Lesson','sparring','Blue belt+'],['15:00-15:40','Little Dragon','dragon','Ages 3-5'],['16:00-16:55','Kid Lesson','kid','Ages 6-10'],['17:00-17:40','Little Dragon','dragon','Ages 3-5'],['18:00-18:55','Kid Lesson','kid','Ages 6-10'],['19:00-19:55','Sparring Lesson','sparring','Blue belt+']],Saturday:[['09:00-09:55','Kid Lesson','kid','Ages 6-10'],['10:00-10:40','Little Dragon','dragon','Ages 3-5'],['11:00-11:55','Kid Lesson','kid','Ages 6-10'],['12:00-12:55','Teen & Adults','teen','Above 11']]};
function el(id){return document.getElementById(id)}
function ic(id){return '<svg><use href="#'+id+'"></use></svg>'}
function bootStyles(){['css/schedule.css','css/chunk3-dashboard.css','css/parent-portal.css','css/calendar-grid.css'].forEach(function(p){var l=document.createElement('link');l.rel='stylesheet';l.href=p;document.head.appendChild(l)});var css='.role-switcher{display:flex;gap:6px;margin:10px 0 0}.role-switcher button{border:1px solid #e5e7eb;background:#fff;border-radius:999px;padding:7px 10px;font-weight:900;font-size:12px}.role-switcher button.active{background:#111827;color:#fff}.demo-lock{border:1px dashed #f59e0b;background:#fffbeb;border-radius:14px;padding:14px;color:#92400e}.hero{background:transparent!important;box-shadow:none!important;border:0!important;padding:0!important;min-height:auto!important;margin:0 0 14px!important}.hero:after,.hero-kicker{display:none!important}.hero h1{font-family:Inter,Arial,sans-serif!important;font-size:22px!important;margin:0 0 4px!important}.hero p{font-size:14px!important;color:#64748b!important;margin:0!important}.metrics{grid-template-columns:repeat(5,1fr)!important;gap:12px!important;margin:14px 0!important}.metric-card{border-radius:12px!important;min-height:90px!important;padding:14px!important}.metric-card strong{font-family:Inter,Arial,sans-serif!important;font-size:26px!important}.metric-icon{width:48px!important;height:48px!important;border-radius:50%!important}@media(max-width:1200px){.metrics{grid-template-columns:repeat(2,1fr)!important}}';document.head.insertAdjacentHTML('beforeend','<style>'+css+'</style>')}
function roleAllowed(view){if(currentRole==='Admin')return true;if(currentRole==='Instructor')return ['dashboard','students','classes','attendance','progress','reports'].indexOf(view)>-1;if(currentRole==='Parent')return ['dashboard','classes','attendance','progress','payments'].indexOf(view)>-1;return true}
function renderHero(){el('hero').innerHTML='<h1>'+currentRole+' Dashboard</h1><p>Demo mode: navigation changes by role and every tab now renders a distinct screen.</p><div class="role-switcher"><button data-role="Admin">Admin</button><button data-role="Instructor">Instructor</button><button data-role="Parent">Parent</button></div>';var rs=document.querySelectorAll('[data-role]');for(var i=0;i<rs.length;i++){rs[i].classList.toggle('active',rs[i].dataset.role===currentRole);rs[i].onclick=function(){currentRole=this.dataset.role;currentView='dashboard';render()}}}
function renderMetrics(){var h='';for(var i=0;i<metrics.length;i++){h+='<article class="metric-card"><div class="metric-icon">'+ic(metrics[i][3])+'</div><div><span>'+metrics[i][1]+'</span><strong>'+metrics[i][0]+'</strong><small>'+metrics[i][2]+'</small></div></article>'}el('metrics').innerHTML=h}
function scheduleHTML(){var days=Object.keys(schedule),h='<article class="panel"><h2>Weekly Class Schedule</h2><p class="panel-subtitle">Official timetable with class eligibility.</p><div class="calendar-board">';for(var d=0;d<days.length;d++){var day=days[d];h+='<section class="day-column"><h3>'+day+'</h3>';for(var i=0;i<schedule[day].length;i++){var a=schedule[day][i];h+='<article class="lesson-card '+a[2]+'"><strong>'+a[1]+'</strong><span>'+a[0]+'</span><small>'+a[3]+'</small></article>'}h+='</section>'}return h+'</div></article>'}
function analyticsHTML(){return '<div class="side-stack"><article class="panel"><h2>Attendance Overview</h2><div class="ring"><div><strong>87%</strong><span>Average</span></div></div><p class="panel-subtitle">Present 111 · Absent 14 · Late 3</p></article><article class="panel"><h2>Payment Summary</h2><div class="payment-summary"><div class="payment-row"><span>Paid</span><strong>RWF 1.245M</strong></div><div class="payment-row"><span>Pending</span><strong>RWF 245k</strong></div><div class="payment-row"><span>Overdue</span><strong>RWF 180k</strong></div></div></article><article class="panel"><h2>Recent Alerts</h2><div class="alert-item"><strong>7 payments are overdue</strong><br><span>Total RWF 180,000</span></div><div class="alert-item"><strong>Promotion test fees due</strong><br><span>5 students</span></div></article></div>'}
function dashboardHTML(){return '<div class="screen-grid">'+scheduleHTML()+analyticsHTML()+'</div>'}
function studentsHTML(){return '<article class="panel"><h2>Student Management</h2><div class="student-grid"><article class="student-card"><div class="avatar-dot">MP</div><div><strong>Minho Park</strong><span class="belt-tag"><span class="belt-mark belt-yellow"></span>Yellow Belt</span><small>Parent: Mrs. Park · 2 lessons/week · 7/15 lessons</small><div class="progress"><i style="width:47%"></i></div></div><span class="status blue">8 left</span></article><article class="student-card"><div class="avatar-dot">NA</div><div><strong>Niyonsaba Aline</strong><span class="belt-tag"><span class="belt-mark belt-green-stripe"></span>Green Stripe</span><small>3 lessons/week · promotion-ready</small><div class="progress"><i style="width:96%"></i></div></div><span class="status green">Ready</span></article></div></article>'}
function attendanceHTML(){return '<article class="panel"><h2>Attendance & Promotion Eligibility</h2><p class="panel-subtitle">Minimum 15 lessons required before promotion testing.</p><div class="student-grid"><article class="student-card"><div class="avatar-dot">MP</div><div><strong>Minho Park</strong><small>7 attended · 8 remaining</small><div class="progress"><i style="width:47%"></i></div></div><span class="status blue">Not yet</span></article><article class="student-card"><div class="avatar-dot">NA</div><div><strong>Niyonsaba Aline</strong><small>18 attended · eligible</small><div class="progress"><i style="width:100%"></i></div></div><span class="status green">Eligible</span></article></div></article>'}
function progressHTML(){return '<article class="panel"><h2>Belt Passport & Poomsae</h2><div class="belt-road"><article class="belt-step"><span class="belt-mark belt-white"></span><strong>White</strong><small>Kibon</small></article><article class="belt-step"><span class="belt-mark belt-yellow"></span><strong>Yellow</strong><small>Taegeuk 1</small></article><article class="belt-step"><span class="belt-mark belt-green-stripe"></span><strong>Green Stripe</strong><small>Taegeuk 2</small></article><article class="belt-step"><span class="belt-mark belt-blue"></span><strong>Blue</strong><small>Taegeuk 5</small></article><article class="belt-step"><span class="belt-mark belt-red"></span><strong>Red</strong><small>Taegeuk 7</small></article><article class="belt-step"><span class="belt-mark belt-black"></span><strong>Black</strong><small>Koryo</small></article></div></article>'}
function paymentsHTML(){return currentRole==='Instructor'?'<article class="demo-lock"><strong>Instructor access:</strong> payments are hidden for this role.</article>':'<article class="panel"><h2>Payments & MTN MoMo</h2><table class="invoice-table"><tr><th>Description</th><th>Amount</th><th>Status</th></tr><tr><td>May monthly fee</td><td>RWF 40,000</td><td><span class="status red">Overdue</span></td></tr><tr><td>Promotion test</td><td>RWF 50,000</td><td><span class="status gold">Pending</span></td></tr><tr><td>Uniform Dobok</td><td>RWF 30,000</td><td><span class="status green">Paid</span></td></tr></table></article>'}
function reportsHTML(){return currentRole==='Parent'?'<article class="demo-lock"><strong>Parent access:</strong> reports are not visible.</article>':'<article class="panel"><h2>Reports</h2><div class="event-item"><strong>Attendance report</strong><br><span>87% average this week</span></div><div class="event-item"><strong>Revenue report</strong><br><span>RWF 1.245M collected</span></div></article>'}
function settingsHTML(){return '<article class="panel"><h2>Settings</h2><p>Role based access is active. Current role: <strong>'+currentRole+'</strong>.</p></article>'}
function blockedHTML(){return '<article class="demo-lock"><strong>Access restricted.</strong><br>This tab is not available for '+currentRole+'. Switch roles above to demonstrate Admin, Instructor, and Parent access.</article>'}
function renderWorkspace(){if(!roleAllowed(currentView)){el('workspace').innerHTML=blockedHTML();return}var map={dashboard:dashboardHTML,students:studentsHTML,classes:scheduleHTML,attendance:attendanceHTML,progress:progressHTML,payments:paymentsHTML,reports:reportsHTML,settings:settingsHTML};el('workspace').innerHTML=(map[currentView]||dashboardHTML)()}
function renderParent(){el('parentPanel').innerHTML='<div class="phone-shell"><div class="phone-screen"><div class="phone-top"><span>9:41</span><span>LTE</span></div><strong>My Child</strong><div class="child-switcher"><button class="child-thumb active"><span class="child-avatar">MP</span>Minho</button><button class="child-thumb"><span class="child-avatar">HP</span>Hana</button><button class="child-thumb"><span class="child-avatar">JP</span>Jisoo</button></div><section class="child-hero"><span>Yellow Belt</span><h2>Minho Park</h2><p>8 lessons remaining before promotion eligibility.</p></section><article class="phone-card"><strong>Next class</strong><span>Tuesday · Kid Lesson · 16:00</span></article><article class="phone-card"><strong>Payment Due</strong><span>RWF 40,000 · MTN MoMo</span></article><article class="phone-card"><strong>Promotion readiness</strong><div class="progress"><i style="width:47%"></i></div></article><nav class="phone-bottom-nav"><span class="active">Home</span><span>Classes</span><span>Progress</span><span>Pay</span></nav></div></div>'}
function renderNav(){var b=document.querySelectorAll('[data-view]');for(var i=0;i<b.length;i++){var ok=roleAllowed(b[i].dataset.view);b[i].style.opacity=ok?'1':'.35';b[i].classList.toggle('active',b[i].dataset.view===currentView);b[i].onclick=function(){currentView=this.dataset.view;render()}}}
function render(){renderHero();renderMetrics();renderWorkspace();renderParent();renderNav()}
document.addEventListener('DOMContentLoaded',function(){bootStyles();render()});
