var currentView = 'dashboard';
var views = {
  dashboard: ['Dojang pulse', 'Today\'s academy command center', 'Live classes, attendance, payments, and promotion readiness in one premium sports-tech dashboard.'],
  students: ['Athlete development', 'Every student has a journey', 'Profiles combine guardians, subscription plans, lesson counts, belt passport, and readiness progress.'],
  classes: ['Training command center', 'Weekly schedule, redesigned', 'A visual training calendar with color-coded classes, age rules, and belt eligibility.'],
  attendance: ['15 lesson rule', 'Attendance becomes promotion intelligence', 'Track lessons attended, lessons remaining, and consistency before promotion testing.'],
  progress: ['Belt advancement', 'Progression is the product language', 'Belts, poomsae, techniques, instructor approval, and payment status combine into readiness.'],
  payments: ['MTN MoMo billing', 'Payments that feel modern', 'Monthly fees, uniforms, and promotion tests are organized into parent-friendly RWF invoices.'],
  reports: ['Operations intelligence', 'Alerts before problems become admin work', 'See overdue payments, promotion fee reminders, class capacity, and upcoming academy events.'],
  settings: ['Accessibility and device fit', 'Designed for desktop, tablet, and phone', 'The app supports light, dark, high contrast, and adjustable text size.']
};
var metrics = [
  ['128', 'Total students', '6 joined this month', 'icon-students'],
  ['87%', 'Attendance today', '74 expected students', 'icon-check'],
  ['12', 'Promotion ready', '15 lesson rule applied', 'icon-belt'],
  ['RWF 180k', 'Pending payments', 'MoMo reminders due', 'icon-payments']
];
var schedule = {
  Monday: [['13:00-14:00','Women’s Lesson','women','Women focused training'],['17:00-17:55','Kid Lesson','kid','Ages 6-10'],['18:00-18:55','Teen & Adults','teen','Above 11 years'],['19:00-19:55','Teen & Adults','teen','Above 11 years']],
  Tuesday: [['16:00-16:55','Kid Lesson','kid','Ages 6-10'],['17:00-17:40','Little Dragon','dragon','Ages 3-5'],['18:00-18:55','Kid Lesson','kid','Ages 6-10'],['19:00-19:55','Sparring Lesson','sparring','Blue belt and above']],
  Thursday: [['17:00-17:55','Kid Lesson','kid','Ages 6-10'],['18:00-18:55','Teen & Adults','teen','Above 11 years']],
  Friday: [['14:00-14:55','Sparring Lesson','sparring','Blue belt and above'],['15:00-15:40','Little Dragon','dragon','Ages 3-5'],['16:00-16:55','Kid Lesson','kid','Ages 6-10'],['17:00-17:40','Little Dragon','dragon','Ages 3-5'],['18:00-18:55','Kid Lesson','kid','Ages 6-10'],['19:00-19:55','Sparring Lesson','sparring','Blue belt and above']],
  Saturday: [['09:00-09:55','Kid Lesson','kid','Ages 6-10'],['10:00-10:40','Little Dragon','dragon','Ages 3-5'],['11:00-11:55','Kid Lesson','kid','Ages 6-10'],['12:00-12:55','Teen & Adults','teen','Above 11 years']]
};
function el(id){return document.getElementById(id);}
function icon(id){return '<svg><use href="#'+id+'"></use></svg>';}
function belt(cls){return '<span class="belt-mark '+cls+'"></span>';}
function setDevice(){var w=window.innerWidth;document.documentElement.dataset.device=w<760?'phone':w<1180?'tablet':'desktop';}
function renderHero(){var v=views[currentView]||views.dashboard;el('hero').innerHTML='<span class="hero-kicker">'+v[0]+'</span><h1>'+v[1]+'</h1><p>'+v[2]+'</p><div class="hero-actions"><button class="pill-btn" id="showClasses">Open weekly schedule</button><button class="pill-btn light" id="themeToggle">Light / Dark</button><button class="pill-btn light" id="contrastToggle">High contrast</button></div>';el('showClasses').onclick=function(){currentView='classes';render();};el('themeToggle').onclick=function(){var h=document.documentElement;h.dataset.theme=h.dataset.theme==='dark'?'light':'dark';};el('contrastToggle').onclick=function(){document.documentElement.classList.toggle('high-contrast');};}
function renderMetrics(){var html='';for(var i=0;i<metrics.length;i++){html+='<article class="metric-card"><div class="metric-icon">'+icon(metrics[i][3])+'</div><div><span>'+metrics[i][1]+'</span><strong>'+metrics[i][0]+'</strong><small>'+metrics[i][2]+'</small></div></article>';}el('metrics').innerHTML=html;}
function scheduleHTML(){var html='<article class="panel"><h2>Han Taekwondo Korea weekly schedule</h2><p class="panel-subtitle">Color-coded training calendar based on the official timetable brief.</p><div class="calendar-board">';var days=Object.keys(schedule);for(var d=0;d<days.length;d++){var day=days[d];html+='<section class="day-column"><h3>'+day+'</h3>';for(var i=0;i<schedule[day].length;i++){var a=schedule[day][i];html+='<article class="lesson-card '+a[2]+'"><strong>'+a[1]+'</strong><span>'+a[0]+'</span><small>'+a[3]+'</small></article>';}html+='</section>';}html+='</div><div class="legend-row"><span class="legend-pill women"><i></i>Women</span><span class="legend-pill kid"><i></i>Kid</span><span class="legend-pill dragon"><i></i>Little Dragon</span><span class="legend-pill teen"><i></i>Teen & Adults</span><span class="legend-pill sparring"><i></i>Sparring</span></div></article>';return html;}
function studentsHTML(){var students=[['MP','Minho Park','Yellow Belt','belt-yellow','Mrs. Jiwon Park','2 lessons / week','67','8 lessons left','blue'],['NA','Niyonsaba Aline','Green Stripe','belt-green-stripe','Aline Family','3 lessons / week','92','Ready','green'],['UD','Umutoni Diane','Blue Stripe','belt-blue-stripe','Umutoni Family','2 lessons / week','88','Ready','green']];var html='<article class="panel"><h2>Student command center</h2><div class="student-grid">';for(var i=0;i<students.length;i++){var s=students[i];html+='<article class="student-card"><div class="avatar-dot">'+s[0]+'</div><div><strong>'+s[1]+'</strong><span class="belt-tag">'+belt(s[3])+s[2]+'</span><small>'+s[4]+' · '+s[5]+'</small><div class="progress"><i style="width:'+s[6]+'%"></i></div></div><span class="status '+s[8]+'">'+s[7]+'</span></article>';}return html+'</div></article>';}
function progressHTML(){var names=[['White Belt','belt-white','Kibon'],['Yellow Belt','belt-yellow','Taegeuk 1'],['Green Stripe','belt-green-stripe','Taegeuk 2'],['Blue Stripe','belt-blue-stripe','Taegeuk 4'],['Blue Belt','belt-blue','Taegeuk 5'],['Red Belt','belt-red','Taegeuk 7'],['Black Belt','belt-black','Koryo']];var html='<article class="panel"><h2>Digital belt passport</h2><div class="belt-road">';for(var i=0;i<names.length;i++){html+='<article class="belt-step">'+belt(names[i][1])+'<strong>'+names[i][0]+'</strong><small>'+names[i][2]+'</small></article>';}return html+'</div><h2>Promotion readiness</h2><div class="student-card"><div class="avatar-dot">MP</div><div><strong>Minho Park · Yellow Belt</strong><small>7 / 15 lessons completed</small><div class="progress"><i style="width:47%"></i></div></div><span class="status blue">8 lessons left</span></div></article>';}
function paymentsHTML(){return '<article class="panel"><h2>Payments and invoices</h2><table class="invoice-table"><thead><tr><th>Description</th><th>Due</th><th>Amount</th><th>Status</th></tr></thead><tbody><tr><td>May 2026 Monthly Fee</td><td>May 15</td><td>RWF 40,000</td><td><span class="status red">Overdue</span></td></tr><tr><td>Promotion Test Fee</td><td>May 31</td><td>RWF 50,000</td><td><span class="status gold">Pending</span></td></tr><tr><td>Uniform Dobok</td><td>Apr 20</td><td>RWF 30,000</td><td><span class="status green">Paid</span></td></tr></tbody></table></article>';}
function reportsHTML(){return '<div class="screen-grid"><article class="panel"><h2>Alerts</h2><div class="student-grid"><article class="student-card"><div class="avatar-dot">7</div><div><strong>Overdue payments</strong><small>RWF 180,000 pending</small></div><span class="status red">Urgent</span></article><article class="student-card"><div class="avatar-dot">12</div><div><strong>Promotion-ready students</strong><small>Prepare grading list</small></div><span class="status green">Ready</span></article></div></article><article class="panel"><h2>Upcoming events</h2><p>Promotion Test · May 31</p><p>Poomsae Workshop · June 7</p></article></div>';}
function settingsHTML(){return '<article class="panel"><h2>Accessibility settings</h2><p class="panel-subtitle">Dark mode, high contrast, and device-aware responsive behavior are enabled.</p></article>';}
function dashboardHTML(){return '<div class="screen-grid">'+scheduleHTML()+'<div><article class="panel"><h2>Attendance pulse</h2><div class="ring"><div><strong>87%</strong><span>today</span></div></div></article><article class="panel"><h2>Alerts</h2><p>7 overdue payments</p><p>12 promotion-ready students</p></article></div></div>';}
function renderWorkspace(){var html=currentView==='dashboard'?dashboardHTML():currentView==='students'?studentsHTML():currentView==='classes'?scheduleHTML():currentView==='payments'?paymentsHTML():currentView==='reports'?reportsHTML():currentView==='settings'?settingsHTML():progressHTML();el('workspace').innerHTML=html;}
function renderParent(){el('parentPanel').innerHTML='<div class="phone-shell"><div class="phone-screen"><div class="phone-top"><span>9:41</span><span>LTE</span></div><section class="child-hero"><span>Parent Portal</span><h2>Minho Park</h2><p>Yellow Belt · 8 lessons remaining.</p></section><article class="phone-card"><strong>Next class</strong><span>Tuesday · Kid Lesson · 16:00-16:55</span></article><article class="phone-card"><strong>Payment due</strong><span>RWF 40,000 · MTN MoMo</span></article><article class="phone-card"><strong>Promotion countdown</strong><span>7 / 15 lessons completed</span><div class="progress"><i style="width:47%"></i></div></article></div></div>';}
function renderNav(){var buttons=document.querySelectorAll('[data-view]');for(var i=0;i<buttons.length;i++){buttons[i].classList.toggle('active',buttons[i].dataset.view===currentView);buttons[i].onclick=function(){currentView=this.dataset.view;render();};}}
function render(){setDevice();renderHero();renderMetrics();renderWorkspace();renderParent();renderNav();}
window.addEventListener('resize',setDevice);
document.addEventListener('DOMContentLoaded',render);
