var currentView='dashboard';
var metrics=[['128','Total Students','+6 this month','icon-students'],['87%','Attendance Today','111 / 128 present','icon-check'],['14','Ready for Promotion','View list','icon-belt'],['RWF 245k','Pending Payments','23 invoices','icon-payments'],['RWF 1.245M','Monthly Revenue','May 2025','icon-report']];
var schedule={Monday:[['13:00-14:00','Women’s Lesson','women','Focused training'],['17:00-17:55','Kid Lesson','kid','Ages 6-10'],['18:00-18:55','Teen & Adults','teen','Above 11'],['19:00-19:55','Teen & Adults','teen','Above 11']],Tuesday:[['16:00-16:55','Kid Lesson','kid','Ages 6-10'],['17:00-17:40','Little Dragon','dragon','Ages 3-5'],['18:00-18:55','Kid Lesson','kid','Ages 6-10'],['19:00-19:55','Sparring Lesson','sparring','Blue belt+']],Thursday:[['17:00-17:55','Kid Lesson','kid','Ages 6-10'],['18:00-18:55','Teen & Adults','teen','Above 11']],Friday:[['14:00-14:55','Sparring Lesson','sparring','Blue belt+'],['15:00-15:40','Little Dragon','dragon','Ages 3-5'],['16:00-16:55','Kid Lesson','kid','Ages 6-10'],['17:00-17:40','Little Dragon','dragon','Ages 3-5'],['18:00-18:55','Kid Lesson','kid','Ages 6-10'],['19:00-19:55','Sparring Lesson','sparring','Blue belt+']],Saturday:[['09:00-09:55','Kid Lesson','kid','Ages 6-10'],['10:00-10:40','Little Dragon','dragon','Ages 3-5'],['11:00-11:55','Kid Lesson','kid','Ages 6-10'],['12:00-12:55','Teen & Adults','teen','Above 11']]};
function el(id){return document.getElementById(id)}
function ic(id){return '<svg><use href="#'+id+'"></use></svg>'}
function bootStyles(){var a=document.createElement('link');a.rel='stylesheet';a.href='css/schedule.css';document.head.appendChild(a);var b=document.createElement('link');b.rel='stylesheet';b.href='css/chunk3-dashboard.css';document.head.appendChild(b);var css='body{font-family:Inter,Arial,sans-serif!important}.hero{background:transparent!important;box-shadow:none!important;border:0!important;padding:0!important;min-height:auto!important;margin:0 0 14px!important}.hero:after,.hero-kicker{display:none!important}.hero h1{font-family:Inter,Arial,sans-serif!important;font-size:22px!important;line-height:1.2!important;margin:0 0 4px!important}.hero p{font-size:14px!important;color:#64748b!important;margin:0!important}.hero-actions{position:absolute!important;right:330px!important;top:18px!important}.pill-btn{border:1px solid #e5e7eb!important;background:#fff!important;color:#111827!important;border-radius:10px!important;padding:9px 12px!important}.pill-btn:first-child{display:none!important}.metrics{grid-template-columns:repeat(5,1fr)!important;gap:12px!important;margin:14px 0!important}.metric-card{border-radius:12px!important;min-height:90px!important;padding:14px!important}.metric-card strong{font-family:Inter,Arial,sans-serif!important;font-size:26px!important}.metric-icon{width:48px!important;height:48px!important;border-radius:50%!important}@media(max-width:1200px){.hero-actions{position:static!important;margin-top:10px!important}.metrics{grid-template-columns:repeat(2,1fr)!important}}';document.head.insertAdjacentHTML('beforeend','<style>'+css+'</style>')}
function renderHero(){el('hero').innerHTML='<h1>Welcome back, Master Park</h1><p>Here’s what’s happening at Han Taekwondo Korea today.</p><div class="hero-actions"><button class="pill-btn">May 19 – May 25, 2025</button><button class="pill-btn" id="themeToggle">Light / Dark</button></div>';var t=el('themeToggle');if(t){t.onclick=function(){var h=document.documentElement;h.dataset.theme=h.dataset.theme==='dark'?'light':'dark'}}}
function renderMetrics(){var h='';for(var i=0;i<metrics.length;i++){h+='<article class="metric-card"><div class="metric-icon">'+ic(metrics[i][3])+'</div><div><span>'+metrics[i][1]+'</span><strong>'+metrics[i][0]+'</strong><small>'+metrics[i][2]+'</small></div></article>'}el('metrics').innerHTML=h}
function scheduleHTML(){var days=Object.keys(schedule),h='<article class="panel"><h2>Weekly Class Schedule</h2><p class="panel-subtitle">Official Han Taekwondo Korea timetable.</p><div class="calendar-board">';for(var d=0;d<days.length;d++){var day=days[d];h+='<section class="day-column"><h3>'+day+'</h3>';for(var i=0;i<schedule[day].length;i++){var a=schedule[day][i];h+='<article class="lesson-card '+a[2]+'"><strong>'+a[1]+'</strong><span>'+a[0]+'</span><small>'+a[3]+'</small></article>'}h+='</section>'}h+='</div></article>';return h}
function analyticsHTML(){return '<div class="side-stack"><article class="panel"><h2>Attendance Overview</h2><div class="ring"><div><strong>87%</strong><span>Average</span></div></div><p class="panel-subtitle">Present 111 · Absent 14 · Late 3</p></article><article class="panel"><h2>Subscription Plans</h2><p>1 Lesson / Week <strong style="float:right">33%</strong></p><div class="progress"><i style="width:33%"></i></div><p>2 Lessons / Week <strong style="float:right">44%</strong></p><div class="progress"><i style="width:44%"></i></div><p>3 Lessons / Week <strong style="float:right">23%</strong></p><div class="progress"><i style="width:23%"></i></div></article><article class="panel"><h2>Payment Summary</h2><div class="payment-summary"><div class="payment-row"><span>Total invoices</span><strong>RWF 1.67M</strong></div><div class="payment-row"><span>Paid</span><strong>RWF 1.245M</strong></div><div class="payment-row"><span>Pending</span><strong>RWF 245k</strong></div><div class="payment-row"><span>Overdue</span><strong>RWF 180k</strong></div></div></article><article class="panel"><h2>Upcoming Events</h2><div class="event-item"><strong>Promotion Test</strong><br><span>May 31, 2025</span></div><div class="event-item"><strong>Poomsae Workshop</strong><br><span>June 7, 2025</span></div></article><article class="panel"><h2>Recent Alerts</h2><div class="alert-item"><strong>7 payments are overdue</strong><br><span>Total RWF 180,000</span></div><div class="alert-item"><strong>Promotion test fees due</strong><br><span>5 students</span></div></article></div>'}
function dashboard(){return '<div class="screen-grid">'+scheduleHTML()+analyticsHTML()+'</div>'}
function renderWorkspace(){el('workspace').innerHTML=currentView==='classes'?scheduleHTML():dashboard()}
function renderParent(){el('parentPanel').innerHTML='<div class="phone-shell"><div class="phone-screen"><div class="phone-top"><span>9:41</span><span>LTE</span></div><section class="child-hero"><span>Parent Portal</span><h2>Minho Park</h2><p>Yellow Belt · Age 8 · Little Dragon</p></section><article class="phone-card"><strong>Attendance Progress</strong><span>7 / 15 lessons · 8 remaining</span><div class="progress"><i style="width:47%"></i></div></article><article class="phone-card"><strong>Payment Due</strong><span>RWF 40,000 · MTN MoMo</span></article></div></div>'}
function renderNav(){var b=document.querySelectorAll('[data-view]');for(var i=0;i<b.length;i++){b[i].classList.toggle('active',b[i].dataset.view===currentView);b[i].onclick=function(){currentView=this.dataset.view;render()}}}
function render(){renderHero();renderMetrics();renderWorkspace();renderParent();renderNav()}
document.addEventListener('DOMContentLoaded',function(){bootStyles();render()});
